# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axonhub < Formula
  desc "All-in-one AI development platform. Use any SDK, access any model."
  homepage "https://github.com/looplj/axonhub"
  version "0.9.34"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.34/axonhub_0.9.34_darwin_amd64.zip"
      sha256 "5407d89bafe222fd1e4068c7b6b7affae462e1a843dfb3619734d6db984192f3"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.34/axonhub_0.9.34_darwin_arm64.zip"
      sha256 "0bd6825b4b67da73a94c6d64933ec0dc9fe4f96e62606b3df162de5417f052e6"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.34/axonhub_0.9.34_linux_amd64.zip"
      sha256 "8e4cafdc9b179d4a90e8c220f4587cae4f70511c7fcccfc03951017bcb44b4fc"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.34/axonhub_0.9.34_linux_arm64.zip"
      sha256 "ce5102ba48a07a6de7ea1df4367f8b211c0486c1f0a9f44099e02b19adc5df6e"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  def caveats
    <<~EOS
      AxonHub runs with default configuration.
      To customize, create a config file at: #{etc}/axonhub/config.yml

      View current configuration:
        axonhub config preview

      The wrapper starts AxonHub from #{etc}/axonhub automatically.
    EOS
  end

  service do
    run [opt_bin/"axonhub"]
    keep_alive true
  end

  test do
    system "#{bin}/axonhub", "version"
  end
end
