# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axonhub < Formula
  desc "All-in-one AI development platform. Use any SDK, access any model."
  homepage "https://github.com/looplj/axonhub"
  version "1.0.0-beta1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta1/axonhub_1.0.0-beta1_darwin_amd64.zip"
      sha256 "b458c8d254696424c5818feba03499ccdec3345602f87bfeb3f9ff0b6abf11b8"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta1/axonhub_1.0.0-beta1_darwin_arm64.zip"
      sha256 "b3971200de166706e84effa05c7b939e1219014d4e97ca7c56eefe2430af76c8"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta1/axonhub_1.0.0-beta1_linux_amd64.zip"
      sha256 "bd94922e91e5c5aa0078d107d6aa4f8c2a75ac4d12c96d3c46c46bd9211d365a"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta1/axonhub_1.0.0-beta1_linux_arm64.zip"
      sha256 "ea62b0139c96324a1a35f443a0f3c35e8c54e8eaf8d0ad9b2dbfab7a8784e95e"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  def caveats
    <<~EOS
      AxonHub runs with default configuration.
      To customize, create a config file at: #{etc}/axonhub/config.yml

      View current configuration:
        axonhub config preview

      The wrapper starts AxonHub from #{etc}/axonhub automatically.
    EOS
  end

  service do
    run [opt_bin/"axonhub"]
    keep_alive true
  end

  test do
    system "#{bin}/axonhub", "version"
  end
end
