# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axonhub < Formula
  desc "All-in-one AI development platform. Use any SDK, access any model."
  homepage "https://github.com/looplj/axonhub"
  version "1.0.0-beta5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta5/axonhub_1.0.0-beta5_darwin_amd64.zip"
      sha256 "59486591191d0f190fee1d4c7933911012a57014a147743490e5aa7ce1cf9ac7"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta5/axonhub_1.0.0-beta5_darwin_arm64.zip"
      sha256 "583e0abfe11b689f274ec5bd6f6fd657f40dcfba6a73714a9a64a7df9ef3b51f"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta5/axonhub_1.0.0-beta5_linux_amd64.zip"
      sha256 "fa8f764c559965d84c92908a2fc973effce5c569a56843e4771c8fc9c6496bfb"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v1.0.0-beta5/axonhub_1.0.0-beta5_linux_arm64.zip"
      sha256 "789f1ed8500604c29faed9f2def06d1022b696da849d35644191a6d96d46c1c7"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  def caveats
    <<~EOS
      AxonHub runs with default configuration.
      To customize, create a config file at: #{etc}/axonhub/config.yml

      View current configuration:
        axonhub config preview

      The wrapper starts AxonHub from #{etc}/axonhub automatically.
    EOS
  end

  service do
    run [opt_bin/"axonhub"]
    keep_alive true
  end

  test do
    system "#{bin}/axonhub", "version"
  end
end
